#! /bin/bash

trap "kill 0" SIGINT

tmpfile="/tmp/singalong-current-song"

function current_artist {
  echo `osascript -e 'tell application "iTunes" to artist of current track as string'`;
}

function current_track {
  echo `osascript -e 'tell application "iTunes" to name of current track as string'`;
}

function fetch_lyrics {
  local server="http://sing-along.herokuapp.com/lyrics"
  local agent="-A 'Sing-along agent'"

  local result=`curl -s -G "$agent" --data-urlencode "artist=$1" --data-urlencode "title=$2" "$server"`
  echo "$result"
}

artist=`current_artist`
title=`current_track`
prev_artist="$artist"
prev_title="$title"

fetch_lyrics "$artist" "$title" > "$tmpfile"

(
  while true; do
    artist=`current_artist`
    title=`current_track`

    if [ "$title" != "$prev_title" ] || [ "$artist" != "$prev_artist" ]; then
      prev_artist="$artist"
      prev_title="$title"
      fetch_lyrics "$artist" "$title" >> "$tmpfile"
    fi
    sleep 1
  done
)&

less +F "$tmpfile"
